### YamlMime:ManagedReference
items:
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings
  commentId: T:Xunit.FrontControllerFindSettings
  id: FrontControllerFindSettings
  parent: v3.2.0.1:Xunit
  children:
  - v3.2.0.1:Xunit.FrontControllerFindSettings.#ctor(Xunit.Sdk.ITestFrameworkDiscoveryOptions,Xunit.Runner.Common.XunitFilters)
  - v3.2.0.1:Xunit.FrontControllerFindSettings.Filters
  - v3.2.0.1:Xunit.FrontControllerFindSettings.Options
  langs:
  - csharp
  - vb
  name: FrontControllerFindSettings
  nameWithType: FrontControllerFindSettings
  fullName: Xunit.FrontControllerFindSettings
  type: Class
  source:
    remote:
      path: src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
      branch: b2368b05c70a2b4bdc024d177ce7f1a0982eeaae
      repo: https://github.com/xunit/xunit
    id: FrontControllerFindSettings
    path: ../src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
    startLine: 11
  assemblies:
  - xunit.v3.runner.common
  namespace: Xunit
  summary: Contains the information by <xref href="v3.2.0.1:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink%2cXunit.FrontControllerFindSettings)" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public class FrontControllerFindSettings : FrontControllerSettingsBase'
    content.vb: Public Class FrontControllerFindSettings Inherits FrontControllerSettingsBase
  inheritance:
  - System.Object
  - v3.2.0.1:Xunit.FrontControllerSettingsBase
  inheritedMembers:
  - v3.2.0.1:Xunit.FrontControllerSettingsBase.LaunchOptions
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.#ctor(Xunit.Sdk.ITestFrameworkDiscoveryOptions,Xunit.Runner.Common.XunitFilters)
  commentId: M:Xunit.FrontControllerFindSettings.#ctor(Xunit.Sdk.ITestFrameworkDiscoveryOptions,Xunit.Runner.Common.XunitFilters)
  id: '#ctor(Xunit.Sdk.ITestFrameworkDiscoveryOptions,Xunit.Runner.Common.XunitFilters)'
  parent: v3.2.0.1:Xunit.FrontControllerFindSettings
  langs:
  - csharp
  - vb
  name: FrontControllerFindSettings(ITestFrameworkDiscoveryOptions, XunitFilters?)
  nameWithType: FrontControllerFindSettings.FrontControllerFindSettings(ITestFrameworkDiscoveryOptions, XunitFilters?)
  fullName: Xunit.FrontControllerFindSettings.FrontControllerFindSettings(Xunit.Sdk.ITestFrameworkDiscoveryOptions, Xunit.Runner.Common.XunitFilters?)
  type: Constructor
  source:
    remote:
      path: src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
      branch: b2368b05c70a2b4bdc024d177ce7f1a0982eeaae
      repo: https://github.com/xunit/xunit
    id: .ctor
    path: ../src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
    startLine: 11
  assemblies:
  - xunit.v3.runner.common
  namespace: Xunit
  summary: Contains the information by <xref href="v3.2.0.1:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink%2cXunit.FrontControllerFindSettings)" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public FrontControllerFindSettings(ITestFrameworkDiscoveryOptions options, XunitFilters? filters = null)
    parameters:
    - id: options
      type: Xunit.Sdk.ITestFrameworkDiscoveryOptions
      description: The discovery options
    - id: filters
      type: Xunit.Runner.Common.XunitFilters
      description: The optional filters (when not provided, finds all tests)
    content.vb: Public Sub New(options As ITestFrameworkDiscoveryOptions, filters As XunitFilters = Nothing)
  overload: v3.2.0.1:Xunit.FrontControllerFindSettings.#ctor*
  nameWithType.vb: FrontControllerFindSettings.New(ITestFrameworkDiscoveryOptions, XunitFilters)
  fullName.vb: Xunit.FrontControllerFindSettings.New(Xunit.Sdk.ITestFrameworkDiscoveryOptions, Xunit.Runner.Common.XunitFilters)
  name.vb: New(ITestFrameworkDiscoveryOptions, XunitFilters)
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.Filters
  commentId: P:Xunit.FrontControllerFindSettings.Filters
  id: Filters
  parent: v3.2.0.1:Xunit.FrontControllerFindSettings
  langs:
  - csharp
  - vb
  name: Filters
  nameWithType: FrontControllerFindSettings.Filters
  fullName: Xunit.FrontControllerFindSettings.Filters
  type: Property
  source:
    remote:
      path: src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
      branch: b2368b05c70a2b4bdc024d177ce7f1a0982eeaae
      repo: https://github.com/xunit/xunit
    id: Filters
    path: ../src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
    startLine: 19
  assemblies:
  - xunit.v3.runner.common
  namespace: Xunit
  summary: Get the test case filters used during discovery.
  example: []
  syntax:
    content: public XunitFilters Filters { get; }
    parameters: []
    return:
      type: Xunit.Runner.Common.XunitFilters
    content.vb: Public ReadOnly Property Filters As XunitFilters
  overload: v3.2.0.1:Xunit.FrontControllerFindSettings.Filters*
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.Options
  commentId: P:Xunit.FrontControllerFindSettings.Options
  id: Options
  parent: v3.2.0.1:Xunit.FrontControllerFindSettings
  langs:
  - csharp
  - vb
  name: Options
  nameWithType: FrontControllerFindSettings.Options
  fullName: Xunit.FrontControllerFindSettings.Options
  type: Property
  source:
    remote:
      path: src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
      branch: b2368b05c70a2b4bdc024d177ce7f1a0982eeaae
      repo: https://github.com/xunit/xunit
    id: Options
    path: ../src/xunit.v3.runner.common/Frameworks/FrontControllerFindSettings.cs
    startLine: 24
  assemblies:
  - xunit.v3.runner.common
  namespace: Xunit
  summary: The options used during discovery.
  example: []
  syntax:
    content: public ITestFrameworkDiscoveryOptions Options { get; }
    parameters: []
    return:
      type: Xunit.Sdk.ITestFrameworkDiscoveryOptions
    content.vb: Public ReadOnly Property Options As ITestFrameworkDiscoveryOptions
  overload: v3.2.0.1:Xunit.FrontControllerFindSettings.Options*
references:
- uid: v3.2.0.1:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink,Xunit.FrontControllerFindSettings)
  commentId: M:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink,Xunit.FrontControllerFindSettings)
  parent: v3.2.0.1:Xunit.IFrontControllerDiscoverer
  href: Xunit.IFrontControllerDiscoverer.Find.html#Xunit_IFrontControllerDiscoverer_Find_Xunit_Sdk_IMessageSink_Xunit_FrontControllerFindSettings_
  name: Find(IMessageSink, FrontControllerFindSettings)
  nameWithType: IFrontControllerDiscoverer.Find(IMessageSink, FrontControllerFindSettings)
  fullName: Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink, Xunit.FrontControllerFindSettings)
  spec.csharp:
  - uid: v3.2.0.1:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink,Xunit.FrontControllerFindSettings)
    name: Find
    href: Xunit.IFrontControllerDiscoverer.Find.html#Xunit_IFrontControllerDiscoverer_Find_Xunit_Sdk_IMessageSink_Xunit_FrontControllerFindSettings_
  - name: (
  - uid: v3.2.0.1:Xunit.Sdk.IMessageSink
    name: IMessageSink
  - name: ','
  - name: " "
  - uid: v3.2.0.1:Xunit.FrontControllerFindSettings
    name: FrontControllerFindSettings
    href: Xunit.FrontControllerFindSettings.html
  - name: )
  spec.vb:
  - uid: v3.2.0.1:Xunit.IFrontControllerDiscoverer.Find(Xunit.Sdk.IMessageSink,Xunit.FrontControllerFindSettings)
    name: Find
    href: Xunit.IFrontControllerDiscoverer.Find.html#Xunit_IFrontControllerDiscoverer_Find_Xunit_Sdk_IMessageSink_Xunit_FrontControllerFindSettings_
  - name: (
  - uid: v3.2.0.1:Xunit.Sdk.IMessageSink
    name: IMessageSink
  - name: ','
  - name: " "
  - uid: v3.2.0.1:Xunit.FrontControllerFindSettings
    name: FrontControllerFindSettings
    href: Xunit.FrontControllerFindSettings.html
  - name: )
- uid: v3.2.0.1:Xunit
  commentId: N:Xunit
  href: Xunit.html
  name: Xunit
  nameWithType: Xunit
  fullName: Xunit
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: v3.2.0.1:Xunit.FrontControllerSettingsBase
  commentId: T:Xunit.FrontControllerSettingsBase
  parent: v3.2.0.1:Xunit
  href: Xunit.FrontControllerSettingsBase.html
  name: FrontControllerSettingsBase
  nameWithType: FrontControllerSettingsBase
  fullName: Xunit.FrontControllerSettingsBase
- uid: v3.2.0.1:Xunit.FrontControllerSettingsBase.LaunchOptions
  commentId: P:Xunit.FrontControllerSettingsBase.LaunchOptions
  parent: v3.2.0.1:Xunit.FrontControllerSettingsBase
  href: Xunit.FrontControllerSettingsBase.LaunchOptions.html#Xunit_FrontControllerSettingsBase_LaunchOptions
  name: LaunchOptions
  nameWithType: FrontControllerSettingsBase.LaunchOptions
  fullName: Xunit.FrontControllerSettingsBase.LaunchOptions
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: v3.2.0.1:Xunit.IFrontControllerDiscoverer
  commentId: T:Xunit.IFrontControllerDiscoverer
  parent: v3.2.0.1:Xunit
  href: Xunit.IFrontControllerDiscoverer.html
  name: IFrontControllerDiscoverer
  nameWithType: IFrontControllerDiscoverer
  fullName: Xunit.IFrontControllerDiscoverer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.#ctor*
  commentId: Overload:Xunit.FrontControllerFindSettings.#ctor
  href: Xunit.FrontControllerFindSettings.-ctor.html#Xunit_FrontControllerFindSettings__ctor_Xunit_Sdk_ITestFrameworkDiscoveryOptions_Xunit_Runner_Common_XunitFilters_
  name: FrontControllerFindSettings
  nameWithType: FrontControllerFindSettings.FrontControllerFindSettings
  fullName: Xunit.FrontControllerFindSettings.FrontControllerFindSettings
  nameWithType.vb: FrontControllerFindSettings.New
  fullName.vb: Xunit.FrontControllerFindSettings.New
  name.vb: New
- uid: v3.2.0.1:Xunit.Sdk.ITestFrameworkDiscoveryOptions
  commentId: T:Xunit.Sdk.ITestFrameworkDiscoveryOptions
  parent: v3.2.0.1:Xunit.Sdk
  href: Xunit.Sdk.ITestFrameworkDiscoveryOptions.html
  name: ITestFrameworkDiscoveryOptions
  nameWithType: ITestFrameworkDiscoveryOptions
  fullName: Xunit.Sdk.ITestFrameworkDiscoveryOptions
- uid: v3.2.0.1:Xunit.Runner.Common.XunitFilters
  commentId: T:Xunit.Runner.Common.XunitFilters
  parent: v3.2.0.1:Xunit.Runner.Common
  href: Xunit.Runner.Common.XunitFilters.html
  name: XunitFilters
  nameWithType: XunitFilters
  fullName: Xunit.Runner.Common.XunitFilters
- uid: v3.2.0.1:Xunit.Sdk
  commentId: N:Xunit.Sdk
  href: Xunit.html
  name: Xunit.Sdk
  nameWithType: Xunit.Sdk
  fullName: Xunit.Sdk
  spec.csharp:
  - uid: v3.2.0.1:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.2.0.1:Xunit.Sdk
    name: Sdk
    href: Xunit.Sdk.html
  spec.vb:
  - uid: v3.2.0.1:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.2.0.1:Xunit.Sdk
    name: Sdk
    href: Xunit.Sdk.html
- uid: v3.2.0.1:Xunit.Runner.Common
  commentId: N:Xunit.Runner.Common
  href: Xunit.html
  name: Xunit.Runner.Common
  nameWithType: Xunit.Runner.Common
  fullName: Xunit.Runner.Common
  spec.csharp:
  - uid: v3.2.0.1:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.2.0.1:Xunit.Runner
    name: Runner
    href: Xunit.Runner.html
  - name: .
  - uid: v3.2.0.1:Xunit.Runner.Common
    name: Common
    href: Xunit.Runner.Common.html
  spec.vb:
  - uid: v3.2.0.1:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.2.0.1:Xunit.Runner
    name: Runner
    href: Xunit.Runner.html
  - name: .
  - uid: v3.2.0.1:Xunit.Runner.Common
    name: Common
    href: Xunit.Runner.Common.html
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.Filters*
  commentId: Overload:Xunit.FrontControllerFindSettings.Filters
  href: Xunit.FrontControllerFindSettings.Filters.html#Xunit_FrontControllerFindSettings_Filters
  name: Filters
  nameWithType: FrontControllerFindSettings.Filters
  fullName: Xunit.FrontControllerFindSettings.Filters
- uid: v3.2.0.1:Xunit.FrontControllerFindSettings.Options*
  commentId: Overload:Xunit.FrontControllerFindSettings.Options
  href: Xunit.FrontControllerFindSettings.Options.html#Xunit_FrontControllerFindSettings_Options
  name: Options
  nameWithType: FrontControllerFindSettings.Options
  fullName: Xunit.FrontControllerFindSettings.Options
memberLayout: SeparatePages
