### YamlMime:ManagedReference
items:
- uid: v3.1.1.0:Xunit.FrontControllerSettingsBase
  commentId: T:Xunit.FrontControllerSettingsBase
  id: FrontControllerSettingsBase
  parent: v3.1.1.0:Xunit
  children:
  - v3.1.1.0:Xunit.FrontControllerSettingsBase.LaunchOptions
  langs:
  - csharp
  - vb
  name: FrontControllerSettingsBase
  nameWithType: FrontControllerSettingsBase
  fullName: Xunit.FrontControllerSettingsBase
  type: Class
  source:
    remote:
      path: src/xunit.v3.runner.utility/Frameworks/FrontControllerSettingsBase.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: FrontControllerSettingsBase
    path: ../src/xunit.v3.runner.utility/Frameworks/FrontControllerSettingsBase.cs
    startLine: 5
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit
  summary: Base class for all invocations of <xref href="v3.1.1.0:Xunit.IFrontController" data-throw-if-not-resolved="false"></xref> and <xref href="v3.1.1.0:Xunit.IFrontControllerDiscoverer" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public class FrontControllerSettingsBase
    content.vb: Public Class FrontControllerSettingsBase
  inheritance:
  - System.Object
  derivedClasses:
  - v3.1.1.0:Xunit.FrontControllerFindAndRunSettings
  - v3.1.1.0:Xunit.FrontControllerFindSettings
  - v3.1.1.0:Xunit.FrontControllerRunSettings
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: v3.1.1.0:Xunit.FrontControllerSettingsBase.LaunchOptions
  commentId: P:Xunit.FrontControllerSettingsBase.LaunchOptions
  id: LaunchOptions
  parent: v3.1.1.0:Xunit.FrontControllerSettingsBase
  langs:
  - csharp
  - vb
  name: LaunchOptions
  nameWithType: FrontControllerSettingsBase.LaunchOptions
  fullName: Xunit.FrontControllerSettingsBase.LaunchOptions
  type: Property
  source:
    remote:
      path: src/xunit.v3.runner.utility/Frameworks/FrontControllerSettingsBase.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: LaunchOptions
    path: ../src/xunit.v3.runner.utility/Frameworks/FrontControllerSettingsBase.cs
    startLine: 10
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit
  summary: Launch options. Currently only applicable to v3 test projects.
  example: []
  syntax:
    content: public FrontControllerLaunchOptions LaunchOptions { get; }
    parameters: []
    return:
      type: Xunit.FrontControllerLaunchOptions
    content.vb: Public ReadOnly Property LaunchOptions As FrontControllerLaunchOptions
  overload: v3.1.1.0:Xunit.FrontControllerSettingsBase.LaunchOptions*
references:
- uid: v3.1.1.0:Xunit.IFrontController
  commentId: T:Xunit.IFrontController
  parent: v3.1.1.0:Xunit
  href: Xunit.IFrontController.html
  name: IFrontController
  nameWithType: IFrontController
  fullName: Xunit.IFrontController
- uid: v3.1.1.0:Xunit.IFrontControllerDiscoverer
  commentId: T:Xunit.IFrontControllerDiscoverer
  parent: v3.1.1.0:Xunit
  href: Xunit.IFrontControllerDiscoverer.html
  name: IFrontControllerDiscoverer
  nameWithType: IFrontControllerDiscoverer
  fullName: Xunit.IFrontControllerDiscoverer
- uid: v3.1.1.0:Xunit
  commentId: N:Xunit
  href: Xunit.html
  name: Xunit
  nameWithType: Xunit
  fullName: Xunit
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: v3.1.1.0:Xunit.FrontControllerSettingsBase.LaunchOptions*
  commentId: Overload:Xunit.FrontControllerSettingsBase.LaunchOptions
  href: Xunit.FrontControllerSettingsBase.LaunchOptions.html#Xunit_FrontControllerSettingsBase_LaunchOptions
  name: LaunchOptions
  nameWithType: FrontControllerSettingsBase.LaunchOptions
  fullName: Xunit.FrontControllerSettingsBase.LaunchOptions
- uid: v3.1.1.0:Xunit.FrontControllerLaunchOptions
  commentId: T:Xunit.FrontControllerLaunchOptions
  parent: v3.1.1.0:Xunit
  href: Xunit.FrontControllerLaunchOptions.html
  name: FrontControllerLaunchOptions
  nameWithType: FrontControllerLaunchOptions
  fullName: Xunit.FrontControllerLaunchOptions
memberLayout: SeparatePages
